-- Club historical statistics editable from the NFC Lichnov admin.
-- Apply through the Supabase SQL editor or migration workflow before using /admin/statistiky.

create table if not exists public.club_player_stats (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) > 0),
  goals integer not null default 0 check (goals >= 0),
  matches integer not null default 0 check (matches >= 0),
  source_order integer not null unique,
  facr_player_id bigint,
  active boolean not null default false,
  needs_review boolean not null default false,
  updated_at timestamptz
);

create table if not exists public.club_seasons (
  ordinal integer primary key,
  season text not null unique check (char_length(trim(season)) > 0),
  matches integer not null default 0 check (matches >= 0),
  record text not null default '',
  score text not null default '',
  points integer not null default 0,
  competition text not null default '',
  position integer not null default 0 check (position >= 0),
  incomplete boolean not null default false,
  outcome text check (outcome in ('promotion', 'relegation')),
  next_competition text,
  updated_at timestamptz
);

create table if not exists public.club_stats_audit (
  id bigint generated always as identity primary key,
  entity_type text not null check (entity_type in ('player', 'season')),
  entity_key text not null,
  action text not null check (action in ('insert', 'update', 'delete')),
  changed_at timestamptz not null default now(),
  changed_by uuid,
  changed_by_email text,
  before_data jsonb,
  after_data jsonb
);

create table if not exists public.club_stats_last_edit (
  entity_type text not null check (entity_type in ('player', 'season')),
  entity_key text not null,
  changed_at timestamptz not null,
  changed_by uuid,
  changed_by_email text,
  primary key (entity_type, entity_key)
);

create index if not exists club_player_stats_facr_idx
  on public.club_player_stats (facr_player_id)
  where facr_player_id is not null;

create index if not exists club_player_stats_active_idx
  on public.club_player_stats (active, matches desc, goals desc);

create index if not exists club_stats_audit_entity_idx
  on public.club_stats_audit (entity_type, entity_key, changed_at desc);

insert into public.club_player_stats (name, goals, matches, source_order)
values
('Michna Jiří', 18, 609, 1),
('Babinec Radim', 33, 563, 2),
('Kašpárek Antonín', 162, 540, 3),
('Kahánek Mojmír', 18, 533, 4),
('Gold Josef', 24, 479, 5),
('Drozd Pavel', 11, 472, 6),
('Drozd Miroslav', 22, 453, 7),
('Pustějovský Lubomír', 7, 423, 8),
('Mrkvan Rastislav', 24, 417, 9),
('Kupčák Milan', 3, 364, 10),
('Kandráč Milan', 3, 347, 11),
('Příhoda Petr (st.)', 53, 335, 12),
('Laga Jiří', 0, 335, 13),
('Tichavský Petr', 105, 334, 14),
('Beneš Jiří', 126, 331, 15),
('Mynář Miroslav', 6, 324, 16),
('Mamula Petr', 0, 305, 17),
('Bartoš Gunter', 3, 292, 18),
('Šudák Radim', 124, 285, 19),
('Klimeš Ondřej', 68, 284, 20),
('Drozd Jaromír', 26, 284, 21),
('Suda Pavel', 59, 280, 22),
('Drozd Zdeněk', 3, 264, 23),
('Freisler Petr', 32, 256, 24),
('Fiala Jiří', 4, 250, 25),
('Bumbalík Karel', 66, 247, 26),
('Osterezy Pavel', 11, 246, 27),
('Chlebek Tomáš', 17, 238, 28),
('Drozd Ladislav', 17, 236, 29),
('Kečkeš Zdeněk', 18, 235, 30),
('Vaněk Ladislav (st.)', 3, 234, 31),
('Mechl Ladislav', 20, 231, 32),
('Neckář Jan', 26, 220, 33),
('Špaček Vladimír', 15, 216, 34),
('Trompisch Eduard', 2, 212, 35),
('Čapka Jaroslav', 23, 211, 36),
('Hanzelka Radek', 29, 205, 37),
('Ostrý Zdeněk', 19, 201, 38),
('Klimek Adam', 2, 199, 39),
('Vrobel Miroslav', 28, 198, 40),
('Příhoda Petr (ml.)', 14, 197, 41),
('Masnica Pavel', 95, 192, 42),
('Hykl Tomáš', 9, 191, 43),
('Polášek Luděk', 41, 187, 44),
('Špaček Martin', 27, 183, 45),
('Ing. Kahánek Jaromír', 52, 180, 46),
('Drozd Petr', 3, 179, 47),
('Gilar Jan', 0, 176, 48),
('Stonawski Daniel', 6, 174, 49),
('Pustějovský Jan', 0, 174, 50),
('Zeman Marek', 35, 172, 51),
('Babič Květoslav', 9, 162, 52),
('Belica Jano', 0, 158, 53),
('Pacal Jiří', 4, 157, 54),
('Kocurek František', 5, 155, 55),
('Palo František', 112, 153, 56),
('Ing. Tichavský Dušan', 1, 149, 57),
('Petr Jiří', 9, 147, 58),
('Chytil Ladislav', 18, 145, 59),
('Holík Milan', 13, 145, 60),
('Spíšek Boh.', 4, 145, 61),
('Polívka Antonín', 2, 144, 62),
('Pančocha Karel', 54, 142, 63),
('Lichnovský Libor', 4, 142, 64),
('Ing. Fajkus Zd.', 7, 141, 65),
('Drozd Tomáš', 2, 141, 66),
('Vaverka Roman', 9, 140, 67),
('Babinec Jara', 19, 139, 68),
('Gold Petr', 8, 137, 69),
('Veselka Lubomír', 0, 132, 70),
('Kocourek Karel', 7, 130, 71),
('Kohut Igor', 12, 128, 72),
('Chlebek Richard', 8, 127, 73),
('Dobečka Zd.', 1, 127, 74),
('Pustějovský Zdeněk', 0, 127, 75),
('Bendik Milan', 40, 126, 76),
('Klečanský Marek', 13, 125, 77),
('Koudelák Jara', 0, 124, 78),
('Žaček Petr', 13, 123, 79),
('Dědík Lukáš', 50, 120, 80),
('Damek Dalibor', 10, 117, 81),
('Veselka Josef', 54, 116, 82),
('Borsík Alois', 12, 114, 83),
('Jeřábek Lubomír', 4, 114, 84),
('Švrček David', 14, 112, 85),
('Růžička Michal', 25, 105, 86),
('Kahánek Luďa', 2, 102, 87),
('Havrlant Radomír', 8, 101, 88),
('Beňo Pavel', 4, 100, 89),
('Holub Přemysl', 3, 97, 90),
('Špaček Alois', 1, 96, 91),
('Rypár Ivo', 1, 95, 92),
('Růžička Tomáš', 0, 92, 93),
('Pustějovský Martin', 4, 88, 94),
('Janák Jakub', 7, 87, 95),
('Chromečka Ondřej', 24, 86, 96),
('Kudělka Tomáš', 12, 86, 97),
('Robeš Daniel', 3, 85, 98),
('Špaček Svaťa', 0, 85, 99),
('Kučera Jan', 2, 84, 100),
('Raška Jaromír', 23, 83, 101),
('Dočkalík Roman', 4, 83, 102),
('Bauman Petr', 4, 82, 103),
('Musil František', 4, 81, 104),
('Horečka Lubomír', 1, 78, 105),
('Březina Vlasta', 4, 77, 106),
('Míček Martin', 3, 76, 107),
('Gerlich Čestmír', 2, 76, 108),
('Weber Jaromír', 0, 75, 109),
('Mičulka Petr', 0, 75, 110),
('Dobečka Lub.', 0, 74, 111),
('Švrček Zdeněk', 0, 73, 112),
('Horečka Čestmír', 0, 73, 113),
('Drozd Jiří', 0, 73, 114),
('Skyba Ladislav', 7, 71, 115),
('Harabiš Kamil', 2, 70, 116),
('Kvita Jaroslav', 0, 70, 117),
('Mikunda Jiří', 0, 69, 118),
('Marek Jiří', 27, 67, 119),
('Božík Miroslav', 3, 67, 120),
('Klimeš Jan', 0, 67, 121),
('Hořelka Václav', 16, 66, 122),
('Špaček Petr ťop', 0, 65, 123),
('Harabiš Lubomír', 1, 63, 124),
('Šimek Radim', 11, 62, 125),
('Olšák Miroslav', 0, 62, 126),
('Tichavský Oldřich', 7, 61, 127),
('Pohlídal Karel', 0, 61, 128),
('Kohut Karel', 0, 61, 129),
('Grossmann Lubomír', 8, 60, 130),
('Hrnčárek Martin', 7, 60, 131),
('Zelínka Vladislav', 3, 60, 132),
('Laga Radek', 0, 60, 133),
('Šablatura Pavel', 4, 58, 134),
('Busek Martin', 11, 57, 135),
('Stonawski Tomáš', 7, 56, 136),
('Špaček Jaroslav', 0, 56, 137),
('Cachnin Pavel', 1, 55, 138),
('Horák Roman', 19, 54, 139),
('Sedlář Roman', 4, 54, 140),
('Rek Jan', 0, 54, 141),
('Čech Marian', 0, 54, 142),
('Satek Jiří', 17, 53, 143),
('Kovalík Jan', 13, 53, 144),
('Bajer Jaroslav', 0, 52, 145),
('Langer Miroslav', 0, 51, 146),
('Klimek Pavel', 4, 50, 147),
('Špaček Michal', 1, 50, 148),
('Lacina Jaroslav', 8, 49, 149),
('Graniák Milan', 2, 48, 150),
('Reibenspiess Leon', 0, 48, 151),
('Krpec Přemek', 33, 47, 152),
('Pluta Zdeněk', 9, 47, 153),
('Křížek Lukáš', 2, 47, 154),
('Hess Jaroslav', 0, 47, 155),
('Fraňo Petr', 9, 46, 156),
('Stanislav Jiří', 2, 46, 157),
('Vašek Roman', 2, 45, 158),
('Pleskot Pavel', 1, 45, 159),
('Pavlík Josef', 1, 45, 160),
('Hyvnar Josef', 0, 45, 161),
('Takač Daniel', 0, 44, 162),
('Hala Petr', 0, 44, 163),
('Lošák Aleš', 9, 43, 164),
('Machala Tomáš', 7, 43, 165),
('Holub Lubomír', 1, 43, 166),
('Kahánek Martin', 6, 42, 167),
('Pustějovský Miroslav', 0, 42, 168),
('Strnka Michal', 1, 41, 169),
('Janovský Dominik', 0, 41, 170),
('Neusehl Dalalibor', 4, 40, 171),
('Hebelka Patrik', 4, 40, 172),
('Špaček Radim', 2, 40, 173),
('Špaček Zdeněk', 0, 40, 174),
('Macíček Marek', 10, 39, 175),
('Pustějovský Vojtěch', 2, 39, 176),
('Vaněček Fr.', 0, 39, 177),
('Štěpán Milan', 7, 37, 178),
('Joukl Václav', 5, 37, 179),
('Tobiáš Luďa', 1, 37, 180),
('Turoň Michael', 0, 37, 181),
('Melčák David', 0, 37, 182),
('Malota Lub.', 0, 37, 183),
('Bartoš Roman', 7, 36, 184),
('Hrazdílek Petr', 4, 36, 185),
('Fukala Pavel', 3, 36, 186),
('Peiger Lumír', 1, 36, 187),
('Černoch Jan', 1, 36, 188),
('Deml Martin', 0, 36, 189),
('Myšinský Marek', 11, 35, 190),
('Kofroň Jaroslav', 1, 35, 191),
('Šíma Marián', 0, 35, 192),
('Hess Jaroslav', 0, 35, 193),
('Svoboda Milan', 5, 34, 194),
('Kulhánek Radim', 0, 34, 195),
('Guttler Otta', 0, 34, 196),
('Beňo Tomáš', 0, 34, 197),
('Hála František', 9, 33, 198),
('Vyvial Miroslav', 6, 33, 199),
('Okřesík Petr', 5, 33, 200),
('Kordoš Adam', 1, 33, 201),
('Veselka Oldřich', 0, 33, 202),
('Lípový Ondřej', 0, 33, 203),
('Daňhel Jan', 1, 32, 204),
('Weber Pavel', 0, 32, 205),
('Svoboda Lubomír', 0, 32, 206),
('Hanzelka Jan', 4, 31, 207),
('Horský Radek', 0, 31, 208),
('Makový Marek', 3, 30, 209),
('Bača Pavel', 2, 30, 210),
('Nohel Petr', 1, 30, 211),
('Vaněk Lad. (ml.)', 0, 30, 212),
('Hajnik Lukáš', 2, 29, 213),
('Klučka Lukáš', 1, 29, 214),
('Schindler Milan', 0, 29, 215),
('Slanina Lukáš', 7, 28, 216),
('Příhoda Radek', 0, 28, 217),
('Mičulka Pavel', 0, 28, 218),
('Gajdoš Jan', 0, 28, 219),
('Adamský Oldřich', 5, 27, 220),
('Prchal Karel', 4, 27, 221),
('Příhoda Zdeněk', 0, 27, 222),
('Kubaník Lukáš', 0, 26, 223),
('Topoli Rudolf', 3, 25, 224),
('Šudák Slavomír', 3, 25, 225),
('Okřesík Jan', 2, 25, 226),
('Svoboda Marian', 1, 25, 227),
('Petráš Radek', 1, 25, 228),
('Kučera Adam', 1, 25, 229),
('Kozelský Vladimír', 0, 25, 230),
('Štěpán Jiří', 2, 24, 231),
('Michálek Patrik', 2, 24, 232),
('Klos Jan', 2, 24, 233),
('Košárek Miroslav', 19, 23, 234),
('Štula Jan', 4, 23, 235),
('Navrátil Jan', 2, 23, 236),
('Krakovský Michal', 2, 23, 237),
('Enčev Radek', 2, 23, 238),
('Melčák Viktor', 1, 23, 239),
('Strnadel Jan', 0, 23, 240),
('Kupčák Radan', 0, 23, 241),
('Dobečka Vlasta', 0, 23, 242),
('Červenka Pavel', 0, 23, 243),
('Blažek Aleš', 0, 23, 244),
('Tobiáš Petr', 7, 22, 245),
('Palacký Adam', 5, 22, 246),
('Kaizrlich Pavel', 4, 22, 247),
('Hebelka David', 4, 22, 248),
('Dostál Filip', 4, 22, 249),
('Neuwirth Milič', 0, 22, 250),
('Kašpárek Jiří', 0, 22, 251),
('Hruška Roman', 7, 21, 252),
('Priesol Stanislav', 5, 21, 253),
('Rek Pavel', 0, 21, 254),
('Březina Radek', 4, 20, 255),
('Marek Petr', 1, 20, 256),
('Křupala Petr', 1, 20, 257),
('Jalůvka Roman', 0, 20, 258),
('Závodný Jiří', 7, 19, 259),
('Janiak Marián', 7, 19, 260),
('Síbrt Jan', 6, 19, 261),
('Verlich Zdeněk', 2, 19, 262),
('Kašpárek Rad.', 0, 19, 263),
('Kalich Jan', 4, 18, 264),
('Macoun Jaroslav', 4, 17, 265),
('Toška Jakub', 3, 17, 266),
('Gazda Tomáš', 3, 17, 267),
('Martiňák Břetislav', 2, 17, 268),
('Hoffman Martin', 0, 17, 269),
('Nenutil Tomáš', 1, 16, 270),
('Minsk David', 1, 16, 271),
('Hanko Michal', 1, 16, 272),
('Horečka Viliám', 0, 16, 273),
('Čapka Zdeněk', 0, 16, 274),
('Hrabovský Miroslav', 8, 15, 275),
('Matonoha Stanislav', 2, 15, 276),
('Kahánek Richard', 0, 15, 277),
('Michálek Jan', 3, 14, 278),
('Mach Matěj', 1, 14, 279),
('Kryzmánek Martin', 0, 14, 280),
('Jurek Vilém', 1, 13, 281),
('Burián David', 1, 13, 282),
('Tobiáš Jiří', 0, 13, 283),
('Suda Jan', 0, 13, 284),
('Sluka Štěpán', 0, 13, 285),
('Polomský Michal', 0, 13, 286),
('Kahánek Přemysl', 0, 13, 287),
('Holub Jaroslav', 0, 13, 288),
('Drozd Lukáš', 0, 13, 289),
('Chromečka Tomáš', 1, 12, 290),
('Blažek Jan', 1, 12, 291),
('Bezděk Lukáš', 1, 12, 292),
('Toman Miroslav', 0, 12, 293),
('Tobiáš Libor', 0, 12, 294),
('Lacina Mir.', 0, 12, 295),
('Čuport Alex', 0, 12, 296),
('Cóka Eugen', 0, 12, 297),
('Biolek Martin', 0, 12, 298),
('Malúš Jiří', 5, 11, 299),
('Hanzelka Radek r.1986', 2, 11, 300),
('Špaček Jiří (ml.)', 0, 11, 301),
('Ollender Martin', 0, 11, 302),
('Kocián Karel', 0, 11, 303),
('Kelnár', 0, 11, 304),
('Bílek Jakub', 0, 11, 305),
('Žabenský Jan', 0, 10, 306),
('Špaček Petr', 0, 10, 307),
('Šereš Vojtech', 0, 10, 308),
('Peiger Tomáš', 0, 10, 309),
('Kunc Jakub', 0, 10, 310),
('Krupa Jiří', 0, 10, 311),
('Kramoliš Pavel', 0, 10, 312),
('Jalůvka Vladan', 0, 10, 313),
('Hanus Adam', 0, 10, 314),
('Melčák Zbyněk', 5, 9, 315),
('Kundl Josef', 2, 9, 316),
('Šulák Pavel', 1, 9, 317),
('Zátopek Libor', 0, 9, 318),
('Špaček Petr lakýrník', 0, 9, 319),
('Šálek Dalibor', 0, 9, 320),
('Růžička Pavel', 0, 9, 321),
('Neusekl Zdeněk', 0, 9, 322),
('Hykel Přemysl', 0, 9, 323),
('Dvořák Petr', 0, 9, 324),
('Raška Adam', 5, 8, 325),
('Gajdušek Daniel', 3, 8, 326),
('Boháč Václav', 3, 8, 327),
('Navrátil Josef', 2, 8, 328),
('Kučera David', 2, 8, 329),
('Hrubý Jakub', 1, 8, 330),
('Vlček Lukáš', 0, 8, 331),
('Pokluda Bedřich', 0, 8, 332),
('Kurečka Marcel', 0, 8, 333),
('Horvát František', 0, 8, 334),
('Burýšek Lukáš', 6, 7, 335),
('Grossmann Dominik', 1, 7, 336),
('Špaček Zbyněk', 0, 7, 337),
('Špaček Jan', 0, 7, 338),
('Radek Petr', 0, 7, 339),
('Mynář Pavel', 0, 7, 340),
('Klimsza Bronislav', 0, 7, 341),
('Kalina Mikuláš', 0, 7, 342),
('Hrňa Petr', 0, 7, 343),
('Bordovský Filip', 0, 7, 344),
('Hubeňák Lukáš', 2, 6, 345),
('Tichavský Miroslav', 1, 6, 346),
('Švasta Michal', 0, 6, 347),
('Skyba Stanislav', 0, 6, 348),
('Rys Jara', 0, 6, 349),
('Kahánek Vlasta', 0, 6, 350),
('Holík Jara (ml.)', 0, 6, 351),
('Dušek Petr', 0, 6, 352),
('Bača Jara', 0, 6, 353),
('Zlý Adam', 0, 5, 354),
('Strnadel Leo', 0, 5, 355),
('Pavelec Martin', 0, 5, 356),
('Majer Vojtěch', 0, 5, 357),
('Kučera R.', 0, 5, 358),
('Gilar Lukáš', 0, 5, 359),
('Fojtášek Robin', 0, 5, 360),
('Figala Pavel', 0, 5, 361),
('Dorňák Don.', 0, 5, 362),
('Csaba Csomes', 0, 5, 363),
('Antoš Patrik', 0, 5, 364),
('Zahradník Ondřej', 1, 4, 365),
('Zbranek Petr', 0, 4, 366),
('Veselý Jakub', 0, 4, 367),
('Urbančík Denis', 0, 4, 368),
('Troškovič Jara', 0, 4, 369),
('Švrček Stan.', 0, 4, 370),
('Špaček Mir.', 0, 4, 371),
('Schindler Václav', 0, 4, 372),
('Pustějovský Jiří', 0, 4, 373),
('Petráš Tomáš', 0, 4, 374),
('Pavliščik', 0, 4, 375),
('Matúš Michal', 0, 4, 376),
('Kupčák Martin', 0, 4, 377),
('Kuchta Lukáš', 0, 4, 378),
('Ing. Demel Mir.', 0, 4, 379),
('Chalupa Jan', 0, 4, 380),
('Hlinka', 0, 4, 381),
('Čeladnik Martin', 0, 4, 382),
('Socha Čeňek', 0, 3, 383),
('Slezák Rostislav', 0, 3, 384),
('Plaček Jaroslav', 0, 3, 385),
('Ondruš Juraj', 0, 3, 386),
('Ferst Petr', 0, 3, 387),
('Bolom Petr', 0, 3, 388),
('Badžgoň František', 0, 3, 389),
('Slováček Jan', 2, 2, 390),
('Kupčík Luboš', 1, 2, 391),
('Žáček Marek', 0, 2, 392),
('Teplárek Ivan', 0, 2, 393),
('Šulák Petr', 0, 2, 394),
('Pokluda', 0, 2, 395),
('Pavlát Ivo', 0, 2, 396),
('Paciorek Roman', 0, 2, 397),
('Kocián Václav', 0, 2, 398),
('Klepáč Jakub', 0, 2, 399),
('Kalich', 0, 2, 400),
('Fojtášek Dan', 0, 2, 401),
('Fizik Jan', 0, 2, 402),
('Dorotík Daniel', 0, 2, 403),
('Čižek', 0, 2, 404),
('Spurný Martin', 1, 1, 405),
('Macháček Matyáš', 1, 1, 406),
('Vávra Radek', 0, 1, 407),
('Vaňek Miroslav', 0, 1, 408),
('Šmíd Otta', 0, 1, 409),
('Šindler (ml.)', 0, 1, 410),
('Sokolovský', 0, 1, 411),
('Rydzák František', 0, 1, 412),
('Pavlát Ondra', 0, 1, 413),
('Mikulenda', 0, 1, 414),
('Maléř Petr', 0, 1, 415),
('Mak Josef.', 0, 1, 416),
('Kupka', 0, 1, 417),
('Kučera Tomáš', 0, 1, 418),
('Koval', 0, 1, 419),
('Koudela', 0, 1, 420),
('Kočíř Jiří', 0, 1, 421),
('Knoll Radek', 0, 1, 422),
('Kašpárek Lukáš', 0, 1, 423),
('Kalus', 0, 1, 424),
('Chytil Zdeněk', 0, 1, 425),
('Huvar Rosťa', 0, 1, 426),
('Galia', 0, 1, 427),
('Čecháček', 0, 1, 428),
('Bauman (ml.)', 0, 1, 429),
('Adamec Ondřej', 0, 1, 430)
on conflict (source_order) do nothing;

insert into public.club_seasons (
  ordinal,
  season,
  matches,
  record,
  score,
  points,
  competition,
  position,
  incomplete,
  outcome,
  next_competition
)
values
(1, '1964/65', 16, '10–2–4', '55:26', 22, '4. třída', 3, false, null, null),
(2, '1965/66', 18, '11–2–5', '58:31', 24, '4. třída', 2, false, 'promotion', '3. třída'),
(3, '1966/67', 22, '6–6–6', '43:49', 18, '3. třída', 8, false, null, null),
(4, '1967/68', 22, '14–1–7', '69:43', 29, '3. třída', 2, false, 'promotion', 'Okresní přebor'),
(5, '1968/69', 24, '10–4–10', '53:42', 24, 'Okresní přebor', 7, false, null, null),
(6, '1969/70', 22, '8–6–8', '45:39', 22, 'Okresní přebor', 6, false, null, null),
(7, '1970/71', 22, '9–4–9', '56:46', 22, 'Okresní přebor', 5, false, null, null),
(8, '1971/72', 22, '14–3–5', '33:22', 31, 'Okresní přebor', 2, false, null, null),
(9, '1972/73', 22, '14–3–5', '55:29', 31, 'Okresní přebor', 1, false, 'promotion', '1. B třída'),
(10, '1973/74', 22, '6–5–11', '32:36', 17, '1. B třída', 9, false, null, null),
(11, '1974/75', 22, '7–1–14', '22:44', 15, '1. B třída', 10, false, null, null),
(12, '1975/76', 22, '8–6–8', '26:29', 22, '1. B třída', 7, false, null, null),
(13, '1976/77', 22, '9–5–8', '34:30', 23, '1. B třída', 7, false, null, null),
(14, '1977/78', 22, '7–5–10', '24:33', 19, '1. B třída', 11, false, null, null),
(15, '1978/79', 22, '8–5–9', '31:38', 21, '1. B třída', 8, false, null, null),
(16, '1979/80', 22, '6–2–14', '25:47', 14, '1. B třída', 12, false, 'relegation', 'Okresní přebor'),
(17, '1980/81', 26, '12–4–10', '56:56', 28, 'Okresní přebor', 7, false, null, null),
(18, '1981/82', 26, '10–6–10', '51:44', 26, 'Okresní přebor', 6, false, null, null),
(19, '1982/83', 26, '16–5–5', '61:36', 37, 'Okresní přebor', 1, false, 'promotion', 'Krajská soutěž'),
(20, '1983/84', 26, '10–7–9', '47:50', 27, 'Krajská soutěž', 4, false, null, null),
(21, '1984/85', 26, '8–4–14', '33:41', 20, 'Krajská soutěž', 10, false, null, null),
(22, '1985/86', 26, '9–5–12', '38:54', 23, 'Krajská soutěž', 10, false, null, null),
(23, '1986/87', 22, '4–2–16', '21:50', 10, 'Krajská soutěž', 12, false, 'relegation', 'Okresní přebor'),
(24, '1987/88', 26, '9–6–11', '34:42', 24, 'Okresní přebor', 10, false, null, null),
(25, '1988/89', 26, '9–5–12', '41:59', 22, 'Okresní přebor', 12, false, null, null),
(26, '1989/90', 26, '7–7–12', '40:50', 21, 'Okresní přebor', 13, false, null, null),
(27, '1990/91', 26, '13–8–5', '47:33', 34, 'Okresní přebor', 2, false, 'promotion', '1. B třída'),
(28, '1991/92', 26, '9–4–13', '42:58', 22, '1. B třída', 12, false, null, null),
(29, '1992/93', 26, '8–7–11', '36:49', 23, '1. B třída', 11, false, null, null),
(30, '1993/94', 26, '12–7–7', '47:35', 31, '1. B třída', 3, false, null, null),
(31, '1994/95', 26, '18–7–1', '73:20', 61, '1. B třída', 1, false, 'promotion', '1. A třída'),
(32, '1995/96', 26, '14–3–9', '50:38', 45, '1. A třída', 3, false, null, null),
(33, '1996/97', 26, '11–4–11', '43:32', 37, '1. A třída', 7, false, null, null),
(34, '1997/98', 26, '9–5–12', '36:41', 32, '1. A třída', 8, false, null, null),
(35, '1998/99', 26, '16–7–3', '65:35', 55, '1. A třída', 1, false, 'promotion', 'Župní přebor SFŽ'),
(36, '1999/2000', 30, '11–6–13', '51:58', 39, 'Župní přebor SFŽ', 9, false, null, null),
(37, '2000/01', 30, '12–6–12', '60:63', 42, 'Župní přebor SFŽ', 8, false, null, null),
(38, '2001/02', 30, '14–5–11', '55:49', 47, 'Župní přebor SFŽ', 4, false, null, null),
(39, '2002/03', 30, '15–7–8', '62:38', 52, 'Krajský přebor', 3, false, null, null),
(40, '2003/04', 30, '14–11–5', '63:38', 53, 'Krajský přebor', 3, false, null, null),
(41, '2004/05', 30, '10–6–14', '54:51', 36, 'Krajský přebor', 9, false, null, null),
(42, '2005/06', 30, '14–5–11', '58:46', 47, 'Krajský přebor', 4, false, null, null),
(43, '2006/07', 30, '11–5–14', '41:66', 38, 'Krajský přebor', 11, false, null, null),
(44, '2007/08', 30, '0–1–29', '28:120', 1, 'Krajský přebor', 16, false, 'relegation', '1. A třída'),
(45, '2008/09', 26, '0–1–25', '9:108', 1, '1. A třída', 14, false, 'relegation', '1. B třída'),
(46, '2009/10', 26, '6–6–14', '36:62', 24, '1. B třída', 11, false, null, null),
(47, '2010/11', 26, '12–3–11', '42:47', 39, '1. B třída', 6, false, null, null),
(48, '2011/12', 26, '9–4–13', '44:67', 31, '1. B třída', 10, false, null, null),
(49, '2012/13', 26, '4–3–19', '31:81', 15, '1. B třída', 14, false, 'relegation', 'Okresní přebor'),
(50, '2013/14', 26, '8–6–12', '49:61', 30, 'Okresní přebor', 10, false, null, null),
(51, '2014/15', 26, '14–3–9', '79:52', 46, 'Okresní přebor', 7, false, null, null),
(52, '2015/16', 26, '9–0–17', '40:64', 29, 'Okresní přebor', 11, false, null, null),
(53, '2016/17', 26, '14–0–12', '59:52', 44, 'Okresní přebor', 5, false, null, null),
(54, '2017/18', 26, '17–0–9', '87:57', 47, 'Okresní přebor', 4, false, null, null),
(55, '2018/19', 26, '10–2–1–13', '42:53', 35, 'Okresní přebor', 10, false, null, null),
(56, '2019/20', 13, '3–1–1–8', '24:35', 12, 'Okresní přebor', 13, true, null, null),
(57, '2020/21', 9, '5–0–1–3', '20:17', 16, 'Okresní přebor', 4, true, null, null),
(58, '2021/22', 26, '6–1–2–17', '42:70', 22, 'Okresní přebor', 14, false, 'relegation', '3. třída'),
(59, '2022/23', 13, '9–2–0–2', '51:25', 31, '3. třída', 2, false, 'promotion', 'Okresní přebor')
on conflict (ordinal) do nothing;


-- Link imported history to current players and add current A-team players missing
-- from the historical source. This NEVER imports matches_count/goals_count from players.
-- Newly inserted rows intentionally start at 0/0 and require manual review.
with men_team as (
  select id
  from public.teams
  where slug = 'muzi'
  limit 1
),
qualifying_players as (
  select distinct on (coalesce(p.facr_player_id::text, p.id::text))
    p.id,
    p.facr_player_id,
    p.first_name,
    p.last_name,
    p.team_id
  from public.players p
  join public.teams t on t.id = p.team_id
  where p.active = true
    and (
      t.slug = 'muzi'
      or (
        p.facr_player_id is not null
        and exists (
          select 1
          from public.players pm
          join men_team mt on mt.id = pm.team_id
          where pm.active = true
            and pm.facr_player_id = p.facr_player_id
        )
      )
      or (
        t.slug = 'dorost'
        and exists (
          select 1
          from public.match_players mp
          join public.matches m on m.id = mp.match_id
          join men_team mt on mt.id = m.team_id
          where mp.player_id = p.id
            and (
              coalesce(mp.lineup_type, '') ilike '%start%'
              or coalesce(mp.lineup_type, '') ilike '%basic%'
              or coalesce(mp.lineup_type, '') ilike '%základ%'
              or coalesce(mp.lineup_type, '') ilike '%zaklad%'
            )
        )
      )
    )
  order by
    coalesce(p.facr_player_id::text, p.id::text),
    case when t.slug = 'muzi' then 0 else 1 end,
    p.id
),
matches_to_link as (
  select
    q.id as current_player_id,
    q.facr_player_id,
    h.id as historical_id,
    row_number() over (
      partition by q.id
      order by h.matches desc, h.goals desc, h.id
    ) as match_rank
  from qualifying_players q
  join public.club_player_stats h
    on lower(trim(h.name)) in (
      lower(trim(concat_ws(' ', q.first_name, q.last_name))),
      lower(trim(concat_ws(' ', q.last_name, q.first_name)))
    )
  where q.facr_player_id is not null
)
update public.club_player_stats h
set
  facr_player_id = link.facr_player_id,
  active = true
from matches_to_link link
where link.match_rank = 1
  and h.id = link.historical_id
  and h.facr_player_id is null;

with men_team as (
  select id
  from public.teams
  where slug = 'muzi'
  limit 1
),
qualifying_players as (
  select distinct on (coalesce(p.facr_player_id::text, p.id::text))
    p.id,
    p.facr_player_id,
    p.first_name,
    p.last_name,
    p.team_id,
    t.slug
  from public.players p
  join public.teams t on t.id = p.team_id
  where p.active = true
    and (
      t.slug = 'muzi'
      or (
        p.facr_player_id is not null
        and exists (
          select 1
          from public.players pm
          join men_team mt on mt.id = pm.team_id
          where pm.active = true
            and pm.facr_player_id = p.facr_player_id
        )
      )
      or (
        t.slug = 'dorost'
        and exists (
          select 1
          from public.match_players mp
          join public.matches m on m.id = mp.match_id
          join men_team mt on mt.id = m.team_id
          where mp.player_id = p.id
            and (
              coalesce(mp.lineup_type, '') ilike '%start%'
              or coalesce(mp.lineup_type, '') ilike '%basic%'
              or coalesce(mp.lineup_type, '') ilike '%základ%'
              or coalesce(mp.lineup_type, '') ilike '%zaklad%'
            )
        )
      )
    )
  order by
    coalesce(p.facr_player_id::text, p.id::text),
    case when t.slug = 'muzi' then 0 else 1 end,
    p.id
),
missing as (
  select q.*
  from qualifying_players q
  where not exists (
    select 1
    from public.club_player_stats h
    where
      (q.facr_player_id is not null and h.facr_player_id = q.facr_player_id)
      or lower(trim(h.name)) in (
        lower(trim(concat_ws(' ', q.first_name, q.last_name))),
        lower(trim(concat_ws(' ', q.last_name, q.first_name)))
      )
  )
),
numbered as (
  select
    missing.*,
    coalesce((select max(source_order) from public.club_player_stats), 0)
      + row_number() over (order by last_name nulls last, first_name nulls last, id) as new_order
  from missing
)
insert into public.club_player_stats (
  name,
  goals,
  matches,
  source_order,
  facr_player_id,
  active,
  needs_review
)
select
  trim(concat_ws(' ', last_name, first_name)),
  0,
  0,
  new_order,
  facr_player_id,
  true,
  true
from numbered;

-- Future controlled synchronization from the admin. It only links/activates current
-- players and inserts missing rows at 0/0; historical totals are never calculated.
create or replace function public.sync_club_player_stats_current()
returns integer
language plpgsql
security definer
set search_path = public, auth
as $
declare
  v_inserted integer := 0;
begin
  if not public.can_edit_content() then
    raise exception 'Not allowed';
  end if;

  with men_team as (
    select id from public.teams where slug = 'muzi' limit 1
  ),
  qualifying_players as (
    select distinct on (coalesce(p.facr_player_id::text, p.id::text))
      p.id,
      p.facr_player_id,
      p.first_name,
      p.last_name,
      t.slug
    from public.players p
    join public.teams t on t.id = p.team_id
    where p.active = true
      and (
        t.slug = 'muzi'
        or (
          p.facr_player_id is not null
          and exists (
            select 1
            from public.players pm
            join men_team mt on mt.id = pm.team_id
            where pm.active = true
              and pm.facr_player_id = p.facr_player_id
          )
        )
        or (
          t.slug = 'dorost'
          and exists (
            select 1
            from public.match_players mp
            join public.matches m on m.id = mp.match_id
            join men_team mt on mt.id = m.team_id
            where mp.player_id = p.id
              and (
                coalesce(mp.lineup_type, '') ilike '%start%'
                or coalesce(mp.lineup_type, '') ilike '%basic%'
                or coalesce(mp.lineup_type, '') ilike '%základ%'
                or coalesce(mp.lineup_type, '') ilike '%zaklad%'
              )
          )
        )
      )
    order by
      coalesce(p.facr_player_id::text, p.id::text),
      case when t.slug = 'muzi' then 0 else 1 end,
      p.id
  ),
  best_links as (
    select distinct on (q.id)
      q.id as current_player_id,
      q.facr_player_id,
      h.id as historical_id
    from qualifying_players q
    join public.club_player_stats h
      on (
        (q.facr_player_id is not null and h.facr_player_id = q.facr_player_id)
        or lower(trim(h.name)) in (
          lower(trim(concat_ws(' ', q.first_name, q.last_name))),
          lower(trim(concat_ws(' ', q.last_name, q.first_name)))
        )
      )
    order by q.id, h.matches desc, h.goals desc, h.id
  )
  update public.club_player_stats h
  set
    facr_player_id = coalesce(h.facr_player_id, link.facr_player_id),
    active = true
  from best_links link
  where h.id = link.historical_id
    and (
      h.active is distinct from true
      or (h.facr_player_id is null and link.facr_player_id is not null)
    );

  with men_team as (
    select id from public.teams where slug = 'muzi' limit 1
  ),
  qualifying_players as (
    select distinct on (coalesce(p.facr_player_id::text, p.id::text))
      p.id,
      p.facr_player_id,
      p.first_name,
      p.last_name,
      t.slug
    from public.players p
    join public.teams t on t.id = p.team_id
    where p.active = true
      and (
        t.slug = 'muzi'
        or (
          p.facr_player_id is not null
          and exists (
            select 1
            from public.players pm
            join men_team mt on mt.id = pm.team_id
            where pm.active = true
              and pm.facr_player_id = p.facr_player_id
          )
        )
        or (
          t.slug = 'dorost'
          and exists (
            select 1
            from public.match_players mp
            join public.matches m on m.id = mp.match_id
            join men_team mt on mt.id = m.team_id
            where mp.player_id = p.id
              and (
                coalesce(mp.lineup_type, '') ilike '%start%'
                or coalesce(mp.lineup_type, '') ilike '%basic%'
                or coalesce(mp.lineup_type, '') ilike '%základ%'
                or coalesce(mp.lineup_type, '') ilike '%zaklad%'
              )
          )
        )
      )
    order by
      coalesce(p.facr_player_id::text, p.id::text),
      case when t.slug = 'muzi' then 0 else 1 end,
      p.id
  ),
  missing as (
    select q.*
    from qualifying_players q
    where not exists (
      select 1
      from public.club_player_stats h
      where
        (q.facr_player_id is not null and h.facr_player_id = q.facr_player_id)
        or lower(trim(h.name)) in (
          lower(trim(concat_ws(' ', q.first_name, q.last_name))),
          lower(trim(concat_ws(' ', q.last_name, q.first_name)))
        )
    )
  ),
  numbered as (
    select
      missing.*,
      coalesce((select max(source_order) from public.club_player_stats), 0)
        + row_number() over (order by last_name nulls last, first_name nulls last, id) as new_order
    from missing
  )
  insert into public.club_player_stats (
    name,
    goals,
    matches,
    source_order,
    facr_player_id,
    active,
    needs_review
  )
  select
    trim(concat_ws(' ', last_name, first_name)),
    0,
    0,
    new_order,
    facr_player_id,
    true,
    true
  from numbered;

  get diagnostics v_inserted = row_count;
  return v_inserted;
end;
$;

revoke all on function public.sync_club_player_stats_current() from public;
grant execute on function public.sync_club_player_stats_current() to authenticated;

create or replace function public.stamp_club_stats_update()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if auth.uid() is not null then
    new.updated_at = now();
  end if;

  return new;
end;
$$;

create or replace function public.audit_club_stats_change()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_entity_type text;
  v_entity_key text;
begin
  -- Ignore migration/seed writes executed without an authenticated editor.
  if auth.uid() is null then
    if tg_op = 'DELETE' then
      return old;
    end if;
    return new;
  end if;

  if tg_table_name = 'club_player_stats' then
    v_entity_type := 'player';
    v_entity_key := coalesce(to_jsonb(new) ->> 'id', to_jsonb(old) ->> 'id');
  else
    v_entity_type := 'season';
    v_entity_key := coalesce(to_jsonb(new) ->> 'ordinal', to_jsonb(old) ->> 'ordinal');
  end if;

  insert into public.club_stats_audit (
    entity_type,
    entity_key,
    action,
    changed_by,
    changed_by_email,
    before_data,
    after_data
  )
  values (
    v_entity_type,
    v_entity_key,
    lower(tg_op),
    auth.uid(),
    auth.jwt() ->> 'email',
    case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) else null end,
    case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) else null end
  );

  insert into public.club_stats_last_edit (
    entity_type,
    entity_key,
    changed_at,
    changed_by,
    changed_by_email
  )
  values (
    v_entity_type,
    v_entity_key,
    now(),
    auth.uid(),
    auth.jwt() ->> 'email'
  )
  on conflict (entity_type, entity_key)
  do update set
    changed_at = excluded.changed_at,
    changed_by = excluded.changed_by,
    changed_by_email = excluded.changed_by_email;

  if tg_op = 'DELETE' then
    return old;
  end if;

  return new;
end;
$$;

drop trigger if exists stamp_club_player_stats_update on public.club_player_stats;
create trigger stamp_club_player_stats_update
before insert or update on public.club_player_stats
for each row execute function public.stamp_club_stats_update();

drop trigger if exists audit_club_player_stats_change on public.club_player_stats;
create trigger audit_club_player_stats_change
after insert or update or delete on public.club_player_stats
for each row execute function public.audit_club_stats_change();

drop trigger if exists stamp_club_seasons_update on public.club_seasons;
create trigger stamp_club_seasons_update
before insert or update on public.club_seasons
for each row execute function public.stamp_club_stats_update();

drop trigger if exists audit_club_seasons_change on public.club_seasons;
create trigger audit_club_seasons_change
after insert or update or delete on public.club_seasons
for each row execute function public.audit_club_stats_change();

alter table public.club_player_stats enable row level security;
alter table public.club_seasons enable row level security;
alter table public.club_stats_audit enable row level security;
alter table public.club_stats_last_edit enable row level security;

drop policy if exists "club player stats public read" on public.club_player_stats;
create policy "club player stats public read"
on public.club_player_stats
for select
using (true);

drop policy if exists "club player stats editor insert" on public.club_player_stats;
create policy "club player stats editor insert"
on public.club_player_stats
for insert
to authenticated
with check (public.can_edit_content());

drop policy if exists "club player stats editor update" on public.club_player_stats;
create policy "club player stats editor update"
on public.club_player_stats
for update
to authenticated
using (public.can_edit_content())
with check (public.can_edit_content());

drop policy if exists "club player stats editor delete" on public.club_player_stats;
create policy "club player stats editor delete"
on public.club_player_stats
for delete
to authenticated
using (public.can_edit_content());

drop policy if exists "club seasons public read" on public.club_seasons;
create policy "club seasons public read"
on public.club_seasons
for select
using (true);

drop policy if exists "club seasons editor insert" on public.club_seasons;
create policy "club seasons editor insert"
on public.club_seasons
for insert
to authenticated
with check (public.can_edit_content());

drop policy if exists "club seasons editor update" on public.club_seasons;
create policy "club seasons editor update"
on public.club_seasons
for update
to authenticated
using (public.can_edit_content())
with check (public.can_edit_content());

drop policy if exists "club seasons editor delete" on public.club_seasons;
create policy "club seasons editor delete"
on public.club_seasons
for delete
to authenticated
using (public.can_edit_content());

drop policy if exists "club stats audit editor read" on public.club_stats_audit;
create policy "club stats audit editor read"
on public.club_stats_audit
for select
to authenticated
using (public.can_edit_content());

drop policy if exists "club stats last edit editor read" on public.club_stats_last_edit;
create policy "club stats last edit editor read"
on public.club_stats_last_edit
for select
to authenticated
using (public.can_edit_content());

revoke all on public.club_player_stats from anon;
revoke all on public.club_seasons from anon;
revoke all on public.club_stats_audit from anon;
revoke all on public.club_stats_audit from authenticated;
revoke all on public.club_stats_last_edit from anon;
revoke all on public.club_stats_last_edit from authenticated;

grant select on public.club_player_stats to anon, authenticated;
grant select on public.club_seasons to anon, authenticated;
grant insert, update, delete on public.club_player_stats to authenticated;
grant insert, update, delete on public.club_seasons to authenticated;
grant select on public.club_stats_audit to authenticated;
grant select on public.club_stats_last_edit to authenticated;

grant usage, select on sequence public.club_player_stats_id_seq to authenticated;
grant select on sequence public.club_stats_audit_id_seq to authenticated;
